#!/bin/bash

WTK=/home/preda/WTK2.2
PREV=$WTK/bin/preverify
PROGUARD="java -jar /home/preda/proguard3.7beta2/lib/proguard.jar @src/proguard.txt"

NAME=JaviaCalc
VERSION="0.0.1"
URL="http://javia.org/"
SRCS="C CalcCanvas Expr History KeyState MoreMath Symbol RMS"

CLASS=$WTK/lib/cldcapi11.jar:$WTK/lib/midpapi20.jar
CLDC=1.1
MIDP=2.0
ICON=a

function genManifest {
echo "MIDlet-1: $NAME, /$ICON, C"
echo MIDlet-Name: $NAME
echo "MIDlet-Vendor: Mihai Preda"
echo MIDlet-Version: $VERSION
echo MicroEdition-Configuration: CLDC-$CLDC
echo MicroEdition-Profile: MIDP-$MIDP
echo MIDlet-Info-URL: $URL
#MIDlet-Install-Notify
#MIDlet-Delete-Notify
#MIDlet-Delete-Confirm
#MIDlet-Description
#MIDlet-Icon
#MIDlet-Data-Size
#MIDlet-Permissions
#MIDlet-Permissions-Opt
}

function genJad {
    cp $1 $2 &&
    echo MIDlet-Jar-URL: $3 >> $2 &&
    echo MIDlet-Jar-Size: `find bin -name $3 -printf %s` >> $2
}

function gen {
FULLNAME=$NAME
echo $FULLNAME
DIRS="class tmp"
rm -rf $DIRS
mkdir -p $DIRS

MANF=tmp/MANIFEST.MF
genManifest > $MANF

set -e
echo Preprocess
rm psrc/*.java
for name in $SRCS ; do
cpp -P -D VERSION="\"$VERSION\"" -D NAME="\"$NAME\"" -D URL="\"$URL\"" src/$name.java psrc/$name.java
done

echo Compilation
CMD="javac -bootclasspath $CLASS -d class psrc/*.java -source 1.4 -target 1.4 -g:none"
#CMD="gcj -C -bootclasspath $CLASS -d class psrc/*.java"
echo $CMD
$CMD
jar cfm tmp/class.jar $MANF -C src $ICON -C class .
if [ a$1 != "a-ng" ] ; then
    $PROGUARD -libraryjars $CLASS -injars tmp/class.jar -outjar tmp/$FULLNAME.jar
else
    cp tmp/class.jar tmp/$FULLNAME.jar
fi

echo Preverify
mkdir -p bin
$PREV -classpath $CLASS -target CLDC$CLDC -d bin tmp/$FULLNAME.jar

genJad $MANF bin/$FULLNAME.jad $FULLNAME.jar
echo
}

gen $*
